### ISSUE TITLE
`carti machine install` providing default bundles for rootfs, ram and rom

### ISSUE THREAD

**Issue by miltonjonat** [createdreamtech/carti#36]
When creating a Carti machine specification, it will often be the case that the user will not specify any particular root file-system, RAM image or ROM image.

The `cartesi-machine` CLI tool defines default assets for those, given by the concatenation of env var `CARTESI_IMAGES_PATH` (`/opt/cartesi/share/images/` by default) and the names `rootfs.ext2`, `linux.bin` and `rom.bin`, which resolve to assets included in the playground docker image.

For Carti, it would probably make more sense to have Carti itself specify "known default bundles" for these assets, and pull them when running `install`.

**Comment by zcstarr** [comment]
I like the idea of turtles all the way down. 

The main blocker on this is probably the lack of a global store. I actually think a global store isn't terrible to write, it would simply replace the current impl and be a composition of two stores the local store and a global store ~/.carti/carti_bundles . 

The order of precedence would be check local then check global. 

With a global store I'd be comfortable getting users to get this setup. 

I think the way I'd go is specifying a set of default cids, and then a carti-default repo with a bundles.json that then shows how to resolve this and then a suggestion upon first running carti to add the repo. 

So then there's no real magic to it, it's all user opt in and if someone sets up a fast repository for these cids , they can ignore the default repo and not have it mess with their expectations.

**Comment by miltonjonat** [comment]
I don't really know what those turtles are there :)

Hmm I had thought the default bundles would come from a "default repo" published at Carti's github (pointing at the assets already being released by Cartesi). In that sense a global store in the user's machine wouldn't be a blocker (although still super-useful to avoid installing those bundles in each project directory over and over again). So you were suggesting that the default bundles would be installed in the machine's global store upon Carti's installation?

**Comment by zcstarr** [comment]
Yeah I think they can, for me the asset size is a kind of big blocker, without a global store. 60mb + 6 +... is a bit painful to shuffle around the whole time. I think it'd be useful to have 

the commandline just prompt the user after the first usages to add the global repo, and install default packages.

I don't want to force it on to the users, because operating context will vary. I can imagine not wanting to do this in the context of a machine you might have on aws where you co locate all the files and storage system  you want and maybe the first commands specify a disk specific bundles.json for those default packages. 

Then it becomes harder to specify where you want to retrieve the package form etc... . It becomes unclear how those packages get resolved as well . If you use -y I'd need a strict local disk / remote ordering policy on package retrieval. 

I just see auto installation as a potential problem area that can be avoided with just nice copy-pasta prompts like brew

**Comment by miltonjonat** [comment]
In general all you said makes sense, but I'm not quite sure what you are proposing as next steps here:
- Add the capacity of having a global store to avoid copying large files around
- Have a default repo published at Carti's Github, and ask the user on setup whether he wants to already install it. Is that it?

In case he doesn't opt in on the default repo, then there would be no default ROM, RAM and rootfs, right? In this case, installing a machine that doesn't define those would result in an incomplete Lua config?
